version: "3"

services:
  webapp:
    container_name: webapp
    image: 'cloud-practice'
    networks:
      - my-network
    ports:
      - 80:80
    depends_on:
      - database

  database:
   container_name: database
   image: 'mysql:5'
   volumes:
     - data-volume:/var/lib/mysql
   networks:
     - my-network
   environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=database
   ports:
     - "3306:3306"

volumes:
  data-volume:

networks:
  my-network: